# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc10ee9f9b037da44bcf9d71d21b4c4b876796fe2283cf78f774f50e2f0c378a35d4b64dc43cae49d9313c0c48f043960fd906a9d223b958c90b84051842d0af

test:
  secret_key_base: 77c470b7817440b1bd8dcbd51e022bd887bfa5478f9c0d0e7a3fc3425e41b02d4d20903cd91670522afe0e6a8b5652c870b0c87733680c4e50a0366e8eada616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
